spring:
    datasource:
        url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net/ad_468a257d7197ff2?user=bd585039c1b141&password=d81a8552
        username: bd585039c1b141
        password: d81a8552
        driver-class-name: com.mysql.jdbc.Driver
    application:
      name: inventory-reactive-service
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.MySQL5Dialect
server:
    port : 8080