spring:
#    datasource:
#        url: jdbc:mysql://localhost:3306/stack?autoReconnect=true&useSSL=false
#        username: root
#        password: root
#        driver-class-name: com.mysql.jdbc.Driver
    application:
      name: inventory-reactive-service
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
server:
    port : 9000